spring:
  application:
    name: spms
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spms?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    static-path-pattern: /static/**

spms:
  security:
    domain: spms.hqido.cc
    secure: true
    httpOnly: false
    secret: ${spms.security.domain}
    sub: ${spring.application.name}
    exp: 7
    whitelist: /api/auth/login,/api/test/**

